worker:
  image:
    repository: 336151728602.dkr.ecr.us-east-1.amazonaws.com/sandbox-1-worker
    tag: 0.0.4
  redis:
    host: infrastructure-prod-eva-redis-master.eva-production.svc.cluster.local:6379
  postgresql:
    server: infrastructure-prod-eva-postgresql.eva-production.svc.cluster.local:5432
    postgresqlUser: postgres
    postgresqlPassword: postgres