apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name-generator
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:336151728602:certificate/2844a5a3-cc60-48f5-8648-0907dee707c6
    alb.ingress.kubernetes.io/group.name: cluster-shared-alb
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: name-generator.sandbox-1.sales-dev.codefresh.io
spec:
  ingressClassName: alb
  rules:
  - host: name-generator.sandbox-1.sales-dev.codefresh.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: name-generator
            port:
              number: 80