apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}
  namespace: #{Kubernetes.Namespace}
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: #{AWS.ACM.CertificateArn}
    alb.ingress.kubernetes.io/group.name: #{ALB.GroupName}
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: #{Application.Domain}
    rollouts.argoproj.io/managed-alb-annotations: '{"#{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}":["alb.ingress.kubernetes.io/actions.#{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}"]}'
  labels:
    app: #{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}
    version: #{Octopus.Release.Number}
spec:
  ingressClassName: alb
  rules:
  - host: #{Application.Domain}
    http:
      paths:
      - backend:
          service:
            name: #{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}
            port:
              number: 80
        path: /
        pathType: Prefix