# Stable Service
apiVersion: v1
kind: Service
metadata:
  name: #{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}
  namespace: #{Kubernetes.Namespace}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: #{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}
---
# Preview/Canary Service
apiVersion: v1
kind: Service
metadata:
  name: #{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}-preview
  namespace: #{Kubernetes.Namespace}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: #{Octopus.Project.Name}-#{Octopus.Environment.Name | ToLower}