apiVersion: v1
kind: Service
metadata:
  name: d20-dice-roller
  labels:
    app: d20-dice-roller
spec:
  type: NodePort
  selector:
    app: d20-dice-roller
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http